export const data = [
  {
    name: "ULTRABOOST 1.0 MIAMI Green",
    image: "/image 1.png",
    price: 200,
    isNew: true,
    isSale: false,
    valSale: 0,
  },
  {
    name: "ADIDAS OZELIA SHOES Green",
    image: "/image 2.png",
    price: 200,
    isNew: true,
    isSale: false,
    valSale: 0,
  },
  {
    name: "ADIDAS 4DFWD 2 RUNNING SHOES",
    image: "/image 3.png",
    price: 200,
    isNew: true,
    isSale: false,
    valSale: 0,
  },
  {
    name: "ULTRABOOST 1.0 MIAMI Green",
    image: "/image 4.png",
    price: 200,
    isNew: false,
    isSale: false,
    valSale: 0,
  },
  {
    name: "ADIDAS OZELIA SHOES Green",
    image: "/image 5.png",
    price: 200,
    isNew: true,
    isSale: false,
    valSale: 0,
  },
  {
    name: "ADIDAS 4DFWD 2 RUNNING SHOES",
    image: "/image 6.png",
    price: 200,
    isNew: false,
    isSale: false,
    valSale: 0,
  },
];
